//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traffic_Simulation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Traffic_Simulation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -13;921
        ///-5;901
        ///2;881
        ///7;864
        ///15;846
        ///21;828
        ///28;810
        ///36;793
        ///41;776
        ///47;762
        ///53;745
        ///60;730
        ///66;713
        ///73;696
        ///78;679
        ///87;663
        ///90;646
        ///98;630
        ///104;614
        ///108;598
        ///116;581
        ///121;565
        ///126;550
        ///132;534
        ///143;521
        ///149;509.
        /// </summary>
        internal static string Aleje_East_Entry_Rondo {
            get {
                return ResourceManager.GetString("Aleje_East_Entry_Rondo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 345;716
        ///334;733
        ///325;750
        ///316;766
        ///308;783
        ///299;800
        ///291;817
        ///281;834
        ///272;851
        ///263;867
        ///255;884
        ///245;900
        ///236;917
        ///227;933
        ///217;950
        ///211;967
        ///202;985
        ///192;1000
        ///183;1016
        ///171;1033
        ///159;1049.
        /// </summary>
        internal static string Aleje_East_Exit_1 {
            get {
                return ResourceManager.GetString("Aleje_East_Exit_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 154;1077
        ///143;1093
        ///131;1111
        ///122;1129
        ///112;1146
        ///103;1164
        ///92;1180
        ///83;1197
        ///75;1215
        ///65;1232
        ///55;1249.
        /// </summary>
        internal static string Aleje_East_Exit_2 {
            get {
                return ResourceManager.GetString("Aleje_East_Exit_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -13;828
        ///-10;810
        ///-5;790
        ///2;770
        ///7;750
        ///13;730
        ///21;710
        ///28;690
        ///33;670
        ///41;650
        ///47;630
        ///53;610
        ///60;590
        ///66;570
        ///68;550
        ///68;530
        ///66;510
        ///66;490
        ///64;470
        ///64;452.
        /// </summary>
        internal static string Aleje_East_Right_Bitwy {
            get {
                return ResourceManager.GetString("Aleje_East_Right_Bitwy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 604;0
        ///599;20
        ///588;37
        ///582;57
        ///574;74
        ///568;91
        ///560;111
        ///552;127
        ///545;147
        ///538;164
        ///530;180
        ///524;197
        ///520;214.
        /// </summary>
        internal static string Aleje_Entry_Left_Bitwy {
            get {
                return ResourceManager.GetString("Aleje_Entry_Left_Bitwy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 648;0
        ///640;20
        ///634;40
        ///626;60
        ///617;80
        ///608;100
        ///599;120
        ///592;140
        ///582;160
        ///572;180
        ///564;200
        ///556;220
        ///548;240
        ///540;260
        ///534;280
        ///528;300.
        /// </summary>
        internal static string Aleje_West_Entry_1 {
            get {
                return ResourceManager.GetString("Aleje_West_Entry_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 514;320
        ///510;340
        ///504;360
        ///497;377
        ///494;394
        ///488;410.
        /// </summary>
        internal static string Aleje_West_Entry_2 {
            get {
                return ResourceManager.GetString("Aleje_West_Entry_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 534;320
        ///528;340
        ///528;360
        ///528;380
        ///530;400
        ///530;420
        ///530;440
        ///534;460
        ///534;480
        ///538;500
        ///540;520.
        /// </summary>
        internal static string Aleje_West_Entry_Bitwy {
            get {
                return ResourceManager.GetString("Aleje_West_Entry_Bitwy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 255;255
        ///261;238
        ///268;221
        ///278;203
        ///287;183.
        /// </summary>
        internal static string Aleje_West_Exit_1 {
            get {
                return ResourceManager.GetString("Aleje_West_Exit_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 295;163
        ///303;143
        ///311;123
        ///320;103
        ///330;83
        ///337;63
        ///347;43
        ///357;23
        ///369;3
        ///375;-17.
        /// </summary>
        internal static string Aleje_West_Exit_2 {
            get {
                return ResourceManager.GetString("Aleje_West_Exit_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0;181
        ///18;188
        ///38;190.
        /// </summary>
        internal static string Bitwy_North_Entry_1 {
            get {
                return ResourceManager.GetString("Bitwy_North_Entry_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 58;200
        ///78;206
        ///98;215
        ///118;221
        ///138;227
        ///158;233
        ///178;238
        ///198;247
        ///218;252
        ///235;261.
        /// </summary>
        internal static string Bitwy_North_Entry_2 {
            get {
                return ResourceManager.GetString("Bitwy_North_Entry_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0;238
        ///18;247
        ///38;252
        ///58;257
        ///78;264
        ///98;272
        ///118;279
        ///138;285
        ///155;292
        ///175;299
        ///192;307
        ///212;315.
        /// </summary>
        internal static string Bitwy_North_Entry_Left_Rondo {
            get {
                return ResourceManager.GetString("Bitwy_North_Entry_Left_Rondo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 146;490
        ///132;479
        ///116;468
        ///98;458
        ///82;447.
        /// </summary>
        internal static string Bitwy_North_Exit_1 {
            get {
                return ResourceManager.GetString("Bitwy_North_Exit_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 62;436
        ///45;427
        ///28;419
        ///10;408
        ///-8;400.
        /// </summary>
        internal static string Bitwy_North_Exit_2 {
            get {
                return ResourceManager.GetString("Bitwy_North_Exit_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 138;381
        ///121;374
        ///104;366
        ///87;359
        ///70;352
        ///53;345
        ///36;337
        ///18;330
        ///0;322.
        /// </summary>
        internal static string Bitwy_North_Left_Exit {
            get {
                return ResourceManager.GetString("Bitwy_North_Left_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 58;178
        ///78;175
        ///98;181
        ///118;185
        ///138;190
        ///158;193
        ///178;193
        ///198;193
        ///218;188
        ///238;181
        ///258;175
        ///275;167.
        /// </summary>
        internal static string Bitwy_North_Right_Aleje {
            get {
                return ResourceManager.GetString("Bitwy_North_Right_Aleje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 568;1252
        ///560;1232
        ///552;1212
        ///545;1192
        ///540;1172.
        /// </summary>
        internal static string Bitwy_South_Entry_1 {
            get {
                return ResourceManager.GetString("Bitwy_South_Entry_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 538;1152
        ///527;1135
        ///517;1120
        ///510;1100
        ///502;1083
        ///497;1066
        ///491;1046
        ///483;1029
        ///475;1013
        ///470;996
        ///464;980
        ///457;963
        ///452;943
        ///445;927
        ///438;911
        ///433;895
        ///426;880
        ///421;863
        ///413;846
        ///406;830
        ///402;813
        ///397;793
        ///389;776
        ///381;760
        ///373;743
        ///368;726
        ///362;710.
        /// </summary>
        internal static string Bitwy_South_Entry_2 {
            get {
                return ResourceManager.GetString("Bitwy_South_Entry_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 491;440
        ///497;460
        ///509;476
        ///517;496
        ///524;516.
        /// </summary>
        internal static string Bitwy_South_Exit_1 {
            get {
                return ResourceManager.GetString("Bitwy_South_Exit_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 538;540
        ///538;560
        ///545;580
        ///548;600
        ///550;620
        ///552;640
        ///556;660
        ///560;680
        ///562;700
        ///564;720
        ///568;740
        ///572;760
        ///574;780
        ///576;800
        ///579;820
        ///582;840
        ///586;860
        ///588;880
        ///592;900
        ///595;920
        ///599;940
        ///604;960
        ///604;980
        ///608;1000
        ///612;1020
        ///615;1040
        ///617;1060
        ///622;1080
        ///622;1100
        ///626;1120
        ///629;1140
        ///634;1160
        ///636;1180
        ///640;1200
        ///645;1220
        ///650;1240
        ///654;1260.
        /// </summary>
        internal static string Bitwy_South_Exit_2 {
            get {
                return ResourceManager.GetString("Bitwy_South_Exit_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 520;1160
        ///502;1146
        ///488;1129
        ///478;1111
        ///470;1093
        ///461;1073
        ///452;1053
        ///445;1033
        ///438;1013
        ///430;993
        ///417;976
        ///402;960
        ///385;947
        ///365;937
        ///345;933
        ///325;933
        ///305;937
        ///285;943
        ///269;957
        ///252;970
        ///236;985
        ///222;1000
        ///208;1016
        ///195;1033
        ///184;1049
        ///171;1063.
        /// </summary>
        internal static string Bitwy_South_Right_Aleje {
            get {
                return ResourceManager.GetString("Bitwy_South_Right_Aleje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 348;685
        ///334;675
        ///319;660
        ///305;645
        ///291;628.
        /// </summary>
        internal static string Rondo_1_East_Entry_Rondo_2 {
            get {
                return ResourceManager.GetString("Rondo_1_East_Entry_Rondo_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 227;318
        ///241;330
        ///255;341
        ///271;355
        ///284;371.
        /// </summary>
        internal static string Rondo_1_Inside_Left_Entry_Rondo_2 {
            get {
                return ResourceManager.GetString("Rondo_1_Inside_Left_Entry_Rondo_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 155;493
        ///161;479
        ///166;463
        ///171;447
        ///178;432
        ///182;416.
        /// </summary>
        internal static string Rondo_1_North_Entry_Rondo_2 {
            get {
                return ResourceManager.GetString("Rondo_1_North_Entry_Rondo_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 475;444
        ///464;460
        ///457;480
        ///452;496
        ///445;513
        ///438;533.
        /// </summary>
        internal static string Rondo_1_South_Entry_Rondo_2 {
            get {
                return ResourceManager.GetString("Rondo_1_South_Entry_Rondo_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 421;544
        ///409;560
        ///397;575
        ///385;588.
        /// </summary>
        internal static string Rondo_1_South_Inside_Rondo_2_Inside {
            get {
                return ResourceManager.GetString("Rondo_1_South_Inside_Rondo_2_Inside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 263;271
        ///281;280
        ///299;289
        ///316;297.
        /// </summary>
        internal static string Rondo_1_West_Entry_Rondo_2 {
            get {
                return ResourceManager.GetString("Rondo_1_West_Entry_Rondo_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 208;540
        ///192;525
        ///177;513
        ///164;500.
        /// </summary>
        internal static string Rondo_2_East_Exit {
            get {
                return ResourceManager.GetString("Rondo_2_East_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 354;475
        ///361;495
        ///365;515
        ///369;535
        ///372;555
        ///375;575.
        /// </summary>
        internal static string Rondo_2_Inside_Left_Entry_Rondo_3 {
            get {
                return ResourceManager.GetString("Rondo_2_Inside_Left_Entry_Rondo_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 192;400
        ///198;381
        ///204;366
        ///212;349
        ///218;335.
        /// </summary>
        internal static string Rondo_2_North_Entry_Rondo_3 {
            get {
                return ResourceManager.GetString("Rondo_2_North_Entry_Rondo_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 430;553
        ///421;573
        ///410;588
        ///402;605
        ///393;620
        ///385;637
        ///377;657
        ///368;671
        ///362;685.
        /// </summary>
        internal static string Rondo_2_South_Exit {
            get {
                return ResourceManager.GetString("Rondo_2_South_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 368;596
        ///348;596
        ///328;600
        ///308;600
        ///288;596.
        /// </summary>
        internal static string Rondo_2_South_Inside_Exit {
            get {
                return ResourceManager.GetString("Rondo_2_South_Inside_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 409;353
        ///426;367
        ///441;380
        ///457;394
        ///475;415.
        /// </summary>
        internal static string Rondo_2_West_Exit {
            get {
                return ResourceManager.GetString("Rondo_2_West_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 375;595
        ///372;615
        ///369;635
        ///365;655.
        /// </summary>
        internal static string Rondo_3_Inside_Left_exit {
            get {
                return ResourceManager.GetString("Rondo_3_Inside_Left_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 227;318
        ///232;302
        ///241;286.
        /// </summary>
        internal static string Rondo_3_North_Exit {
            get {
                return ResourceManager.GetString("Rondo_3_North_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 227;513
        ///217;500
        ///208;483
        ///202;466
        ///198;449
        ///195;429
        ///198;410.
        /// </summary>
        internal static string Rondo_East_Inside {
            get {
                return ResourceManager.GetString("Rondo_East_Inside", resourceCulture);
            }
        }
    }
}
